project:
  type: book
  output-dir: docs

book:
  search: false
  title: "Pour une pédagogie perceptive"
  subtitle: ""
  author: "Matthieu Gaudeau"
  date: "2026"
  chapters:
    - index.qmd
    - 01-Table-des-matieres.qmd
    - 02-Introduction.qmd
    - 03-Chapitre-1.qmd
    - 04-Premiere-exploration.qmd
    - 150-Bibliographie.qmd

bibliography: references.bib

lang: fr
number-sections: false

format:
  html:
    theme: flatly
    css: styles.css
    page-layout: article
  epub:
    cover-image: images/cover-epub.png