project:
  type: book
  output-dir: docs

book:
  search: false
  title: "Pour une pédagogie perceptive"
  subtitle: ""
  author: "Matthieu Gaudeau"
  date: "2026"
  chapters:
    - index.qmd
    - intro.qmd
    - chapitre-1.qmd
    - bibliographie.qmd

bibliography: references.bib

lang: fr
number-sections: false

format:
  html:
    theme: flatly
    css: styles.css
  epub:
    cover-image: cover.png